app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
crud_users:
    resource: '@AppBundle/Resources/config/routing/users.yml'
    prefix: crud/users
    
crud_zawodnik:
    resource: '@AppBundle/Resources/config/routing/zawodnik.yml'
    prefix: crud/zawodnik

rezultaty:
    resource: '@AppBundle/Resources/config/routing/rezultaty.yml'
    prefix: crud/rezultaty
    
settings:
    resource: '@AppBundle/Resources/config/routing/settings.yml'
    prefix: crud/settings

kluby:
    resource: '@AppBundle/Resources/config/routing/kluby.yml'
    prefix: crud/kluby

konkurencja:
    resource: '@AppBundle/Resources/config/routing/konkurencja.yml'
    prefix: crud/konkurencja
    
start:
    resource: '@AppBundle/Resources/config/routing/konkurencja.yml'
    prefix: crud/konkurencja
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"